excluded-comments = [
    """
strong typedefs
    """,

    """
struct StackFrame {
char pad_0000[8+8]; 0x0000
const sdk::REMethodDefinition* method;
char pad_0010[24]; 0x0018
void* in_data; 0x0030 can point to data
void* out_data; 0x0038 can be whatever, can be a dword, can point to data
void* object_ptr; 0x0040 aka "this" pointer
};
    """,

    """
#pragma pack(push, 1)
struct InvokeRet {
union {
std::array<uint8_t, 128> bytes{};
uint8_t byte;
uint16_t word;
uint32_t dword;
float f;
uint64_t qword;
double d;
void* ptr;
};

bool exception_thrown{false};
};
#pragma pack(pop)
    """
]
