[package]
name = "reframework-sys"
version = "0.1.0"
edition = "2021"
links = "reframework"

[lib]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.68"
static-toml = "1"
